query TestGetAllFolders {
  getAllFolders {
    ...ItemFields
    children {
      ...ItemFields
      children {
        ...ItemFields
        children {
          ...ItemFields
          children {
            ...ItemFields
          }
        }
      }
    }
  }
}

fragment ItemFields on FileSystemItem {
  name
  identifier
  description
  path
  type
}
