mutation EditUsers($userId: ID!, $userData: editUser) {
  editUsers(id: $userId, userData: $userData) {
    data {
      ramal_number
      name
      id
      email
    }
    message
    success
  }
}
